[project]
name = "puzzle-agent"
version = "1.0.0"

description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "dotenv>=0.9.9",
    "fastapi>=0.141.1",
    "langchain>=1.4.1",
    "langchain-google-genai>=4.4.0",
    "langgraph>=1.2.11",
    "load-dotenv>=0.1.0",
    "pydantic>=2.13.5",
    "pymongo>=4.18.1",
    "python-dotenv>=1.2.3",
    "uvicorn>=0.53.0",
]

[dependency-groups]
dev = [
    "pytest>=9.1.1",
]

[tool.pytest.ini_options]
pythonpath = ["."]

